/**
 * POST /api/v1/chat — a platform-explainer assistant backed by Groq.
 *
 * Why this lives server-side rather than the frontend calling Groq
 * directly: the API key must never reach the browser. GLOSSARY.md's
 * Golden Rules are explicit that secrets never go in client code, and a
 * key embedded in a frontend bundle is trivially extractable by anyone
 * who opens devtools — it would not be "the gateway's key with extra
 * steps", it would be a public key. This route is the only thing that
 * ever sees GASX_API_GROQ_API_KEY.
 *
 * The assistant is given real, current platform state as context on
 * every request — the live EGSI score, its components, and the AI
 * forecast — fetched the same way GET /api/v1/market already does
 * (deps.aiClient, best-effort). Without this, the model would either
 * refuse to answer "what's the EGSI right now" or, worse, hallucinate a
 * plausible-sounding number. Grounding it in a real reading is what
 * makes "what's the current EGSI" a question this can actually answer
 * rather than guess at.
 *
 * Conversation history is kept client-side and sent whole on every
 * request (this route is stateless), matching how every other route in
 * this gateway works — there is no session store to add.
 */
import type { FastifyInstance } from 'fastify';
import type { GatewayDeps } from '../server.js';

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

interface ChatBody {
  messages?: unknown;
}

const MAX_MESSAGES = 20;
const MAX_MESSAGE_LENGTH = 2000;

function validateMessages(body: ChatBody): ChatMessage[] | string {
  if (!Array.isArray(body.messages) || body.messages.length === 0) {
    return 'messages must be a non-empty array';
  }
  if (body.messages.length > MAX_MESSAGES) {
    return `messages must not exceed ${MAX_MESSAGES} entries`;
  }
  const validated: ChatMessage[] = [];
  for (const entry of body.messages) {
    const role = (entry as { role?: unknown } | null)?.role;
    if (typeof entry !== 'object' || entry === null || (role !== 'user' && role !== 'assistant')) {
      return "each message needs role 'user' or 'assistant'";
    }
    const content = (entry as { content?: unknown }).content;
    if (typeof content !== 'string' || !content.trim()) {
      return 'each message needs non-empty string content';
    }
    if (content.length > MAX_MESSAGE_LENGTH) {
      return `message content must not exceed ${MAX_MESSAGE_LENGTH} characters`;
    }
    validated.push({ role, content });
  }
  return validated;
}

/** Builds the system prompt: static platform description plus whatever
 * live numbers are available right now. Best-effort — a down AI service
 * degrades this to "no live reading available" rather than failing the
 * whole chat request, matching GET /api/v1/market's own tolerance for
 * that dependency being unreachable. */
async function buildSystemPrompt(deps: GatewayDeps): Promise<string> {
  const [egsi, forecast] = await Promise.all([
    deps.aiClient.getCurrentEgsi().catch(() => null),
    deps.aiClient.getForecast().catch(() => null),
  ]);

  const lines = [
    'You are the GASX platform assistant. GASX is an AI-native Ethereum ' +
      'gas futures exchange: it turns Ethereum blockspace congestion into a ' +
      'tradeable market on Sui, hedged with ETH options on Thetanuts (Base ' +
      'mainnet).',
    '',
    'Key facts about the platform:',
    '- EGSI (Ethereum Gas Stress Index) is a computed 0-1000 congestion ' +
      'index built from base fee, block utilization, mempool pressure, fee ' +
      'momentum, gas volatility, DEX activity, and (when available) ETH ' +
      'option implied volatility from Thetanuts.',
    '- EGSI-1H is a one-hour futures contract on that index, settled in ' +
      'USDC on Sui.',
    '- The AI forecast predicts EGSI ahead, with a confidence score and a ' +
      'tail probability of exceeding 500. If no trained model has beaten a ' +
      'naive baseline, the platform serves that baseline instead and says ' +
      'so -- never a number dressed up as more confident than it is.',
    '- Hedging: the platform can request ETH option quotes from Thetanuts ' +
      'to offset ETH-correlated exposure. Hard risk limits (max order size, ' +
      'max slippage, minimum model confidence, max hedge notional) are ' +
      'enforced in the gateway, not by the model -- the AI can request an ' +
      'action, but cannot bypass these limits.',
    '- Depth shown in the order book is indicative, generated by a ' +
      'quoting engine from the AI forecast -- not a live indexed order book.',
    '',
  ];

  if (egsi) {
    lines.push(
      `Current live reading: EGSI = ${Math.round(egsi.score)} (0-1000 scale), ` +
        `as of block ${egsi.block_number}.`,
    );
  } else {
    lines.push('No live EGSI reading is available right now -- say so rather than guessing a number.');
  }

  if (forecast) {
    lines.push(
      `Current AI forecast: expected EGSI ${forecast.expected_egsi.toFixed(1)}, ` +
        `confidence ${Math.round(forecast.confidence * 100)}%, model ${forecast.model_version}.`,
    );
  } else {
    lines.push('No AI forecast is available right now.');
  }

  lines.push(
    '',
    'Answer questions about the platform and these current stats plainly ' +
      'and concisely. If asked about a live number you were not given ' +
      'above, say you do not have that reading rather than inventing one. ' +
      'You are not a financial advisor; do not give trading advice or tell ' +
      'anyone what to buy or sell.',
  );

  return lines.join('\n');
}

export function registerChatRoutes(app: FastifyInstance, deps: GatewayDeps): void {
  app.post<{ Body: ChatBody }>('/api/v1/chat', async (request, reply) => {
    if (!deps.groq?.apiKey) {
      return reply.status(501).send({
        error: 'chat assistant not configured -- set GASX_API_GROQ_API_KEY (see .env.example)',
      });
    }

    const messages = validateMessages(request.body ?? {});
    if (typeof messages === 'string') {
      return reply.status(400).send({ error: messages });
    }

    const systemPrompt = await buildSystemPrompt(deps);

    let groqResponse: Response;
    try {
      groqResponse = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          authorization: `Bearer ${deps.groq.apiKey}`,
        },
        body: JSON.stringify({
          model: deps.groq.model,
          messages: [{ role: 'system', content: systemPrompt }, ...messages],
          temperature: 0.3,
          max_tokens: 500,
        }),
      });
    } catch (err) {
      return reply.status(502).send({ error: `could not reach Groq: ${(err as Error).message}` });
    }

    if (!groqResponse.ok) {
      const body = await groqResponse.text().catch(() => '');
      return reply.status(502).send({
        error: `Groq returned ${groqResponse.status}: ${body.slice(0, 300)}`,
      });
    }

    const payload = (await groqResponse.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    const reply_ = payload.choices?.[0]?.message?.content;
    if (typeof reply_ !== 'string') {
      return reply.status(502).send({ error: 'Groq response did not include a message' });
    }

    return { reply: reply_ };
  });
}
